//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveCheques", ReplyAction="http://tempuri.org/IService/SaveChequesResponse")]
        bool SaveCheques(WCFService.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveCheques", ReplyAction="http://tempuri.org/IService/SaveChequesResponse")]
        System.Threading.Tasks.Task<bool> SaveChequesAsync(WCFService.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChequesPack", ReplyAction="http://tempuri.org/IService/GetChequesPackResponse")]
        WCFService.Cheque[] GetChequesPack(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChequesPack", ReplyAction="http://tempuri.org/IService/GetChequesPackResponse")]
        System.Threading.Tasks.Task<WCFService.Cheque[]> GetChequesPackAsync(int size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsService.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsService.ServiceReference1.IService>, WindowsService.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveCheques(WCFService.Cheque cheque) {
            return base.Channel.SaveCheques(cheque);
        }
        
        public System.Threading.Tasks.Task<bool> SaveChequesAsync(WCFService.Cheque cheque) {
            return base.Channel.SaveChequesAsync(cheque);
        }
        
        public WCFService.Cheque[] GetChequesPack(int size) {
            return base.Channel.GetChequesPack(size);
        }
        
        public System.Threading.Tasks.Task<WCFService.Cheque[]> GetChequesPackAsync(int size) {
            return base.Channel.GetChequesPackAsync(size);
        }
    }
}
