//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService.FakeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FakeServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Save_Cheques", ReplyAction="http://tempuri.org/IService/Save_ChequesResponse")]
        bool Save_Cheques(WCFService.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Save_Cheques", ReplyAction="http://tempuri.org/IService/Save_ChequesResponse")]
        System.Threading.Tasks.Task<bool> Save_ChequesAsync(WCFService.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get_Cheques_Pack", ReplyAction="http://tempuri.org/IService/Get_Cheques_PackResponse")]
        WCFService.Cheque[] Get_Cheques_Pack(int pack_size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get_Cheques_Pack", ReplyAction="http://tempuri.org/IService/Get_Cheques_PackResponse")]
        System.Threading.Tasks.Task<WCFService.Cheque[]> Get_Cheques_PackAsync(int pack_size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsService.FakeServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsService.FakeServiceReference.IService>, WindowsService.FakeServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Save_Cheques(WCFService.Cheque cheque) {
            return base.Channel.Save_Cheques(cheque);
        }
        
        public System.Threading.Tasks.Task<bool> Save_ChequesAsync(WCFService.Cheque cheque) {
            return base.Channel.Save_ChequesAsync(cheque);
        }
        
        public WCFService.Cheque[] Get_Cheques_Pack(int pack_size) {
            return base.Channel.Get_Cheques_Pack(pack_size);
        }
        
        public System.Threading.Tasks.Task<WCFService.Cheque[]> Get_Cheques_PackAsync(int pack_size) {
            return base.Channel.Get_Cheques_PackAsync(pack_size);
        }
    }
}
